name: Deploy Application,
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn.lock') }}   
        
      - name: Install dependencies
        run: npm ci
      
      - name: Lint application
        run: npm run lint
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        